version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/Book?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017" 
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

